### ISSUE TITLE
geosite.db 可以加上tiktok吗？

### ISSUE THREAD

**Issue by Eggku** [MetaCubeX/meta-rules-dat#18]
geosite.db 可以加上tiktok吗？
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/TikTok

**Comment by Larvan2** [comment]
本项目使用的[上游](https://github.com/v2fly/domain-list-community/blob/b5886d54f666a19df4246d4af50dd3290ce41172/data/tiktok#L4)有TikTok的列表
