### ISSUE TITLE
geoip-lite.dat 的 geoip:cn 丢失了 ipv4 信息

### ISSUE THREAD

**Issue by peeweep** [MetaCubeX/meta-rules-dat#20]
geoip-lite.dat 的 geoip:cn https://fars.ee/XdP8

geoip.dat 的 geoip:cn https://fars.ee/USe2

**Comment by peeweep** [comment]
cc @xishang0128

**Comment by xishang0128** [comment]
获取ipv4的时候timeout了,等会更新一下就行
