### ISSUE TITLE
sing分支的bm7规则消失

### ISSUE THREAD

**Issue by LucaLin233** [MetaCubeX/meta-rules-dat#40]
今天重建容器看日志的时候提示规则404，跑上来看了一下确实没有了（
是出于什么原因不再做了呢（

**Comment by xishang0128** [comment]
混合规则集合对于小白来说很可能会导致一些问题,所以应sing-box开发者要求,删除了所有混合的规则集合构建

如有需要,fork一份看commit取消注释即可
