### ISSUE TITLE
请求添加上游V2ray库中的正则规则

### ISSUE THREAD

**Issue by jklolixxs** [MetaCubeX/meta-rules-dat#41]
https://wiki.metacubex.one/config/rules/#domain-regex

现在Meta已经支持域名正则写法了，这样子就可以同步上游V2ray库中的正则域名写法，不然会有不少域名无法匹配到

例如：epicgame规则

epic下载游戏的时候，会有这个域名
epicgames-download1.akamaized.net

而原本geosite会使用正则处理匹配这条
regexp:^epicgames-download\d\.akamaized\.net$

而Meta规则转换后少掉了

以前Meta还不能处理匹配域名正则，但现在可以处理匹配域名正则了，所以请求加上那些缺失的正则域名规则☺️

**Comment by xishang0128** [comment]
https://wiki.metacubex.one/config/rule-providers/content/#domain
