### ISSUE TITLE
建议将dns.msftncsi.com以及www.msftncsi.com加入microsoft@cn列表，因为windows系统通过该url地址的返回状态判断电脑是否联网的

### ISSUE THREAD

**Issue by zypluckyphoenix** [MetaCubeX/meta-rules-dat#46]
若www.msftncsi.com或dns.msftncsi.com的dns解析不及时，会导致系统错误地判断电脑未联网
微软文档：https://learn.microsoft.com/zh-cn/windows-server/networking/ncsi/ncsi-frequently-asked-questions

**Comment by xishang0128** [comment]
https://github.com/v2ray/domain-list-community/blob/master/data/microsoft 向上游反馈
