### ISSUE TITLE
域名错误,望修复

### ISSUE THREAD

**Issue by CaoKang-David** [MetaCubeX/meta-rules-dat#48]
![image](https://github.com/MetaCubeX/meta-rules-dat/assets/19624728/7f418a80-55cb-4fa6-85c1-4ce29f4ecc51)
如图，nintendo.net 写成了nentindo.net

**Comment by xishang0128** [comment]
上游的问题
https://github.com/v2ray/domain-list-community/blob/558eeb914414ff1dc660282e91c6b173646e357a/data/nintendo#L16
