### ISSUE TITLE
域名列表里没有域名，全是IP

### ISSUE THREAD

**Issue by DriverFA** [MetaCubeX/meta-rules-dat#52]
https://github.com/MetaCubeX/meta-rules-dat/blob/sing/geo/geosite/netflix.json
![image](https://github.com/user-attachments/assets/47c955ad-3a63-4751-9ed7-23579a7b1ff7)

**Comment by chunyu-he** [comment]
突然一堆规则失效😑

**Comment by HeInfinity** [comment]
我也是 更新后就出现这个问题了😑
